# Generated by Django 4.0.10 on 2023-10-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('case_status', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('salary_type', models.CharField(max_length=100)),
                ('visa_class', models.CharField(max_length=100)),
            ],
        ),
    ]
