# Generated by Django 4.0.10 on 2023-10-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='case_status',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='visa_class',
        ),
    ]
